[package]
name = "nvidia-video-codec-sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cudarc = "0.9.9"
lazy_static = "1.4.0"

[dev-dependencies]
# dma-buf = "0.3.0"
vulkano = "0.33.0"
